### ISSUE TITLE
Support for Images from Clipboard

### ISSUE THREAD

**Issue by wknupe** [animalnots/BetterChatGPT-VISION#12]
The image support for BetterchatGPT is excellent, but I am curious if it would be possible to enable the use of CTRL-V in the message entry field to insert images directly from the clipboard. This feature would significantly enhance the daily workflow.

At present, the process involves using WIN-Shift-S to capture a portion of the screen, followed by using the file upload button to locate and select the saved screenshot from the "Pictures" folder. Implementing CTRL-V functionality would greatly improve here.

**Comment by animalnots** [comment]
https://github.com/animalnots/BetterChatGPT-VISION/releases/tag/v1.2.0
implemented, thanks for the idea

**Comment by wknupe** [comment]
Excellent. It works beautifully. And you are fast. Thank you very much.
